//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://apiretriever.dankest.ddns.net", ConfigurationName="ServiceReference1.APIRetriever")]
    public interface APIRetriever {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément city de l'espace de noms http://apiretriever.dankest.ddns.net n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WindowsForms1.ServiceReference1.getResultResponse getResult(WindowsForms1.ServiceReference1.getResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsForms1.ServiceReference1.getResultResponse> getResultAsync(WindowsForms1.ServiceReference1.getResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://apiretriever.dankest.ddns.net", Order=0)]
        public WindowsForms1.ServiceReference1.getResultRequestBody Body;
        
        public getResultRequest() {
        }
        
        public getResultRequest(WindowsForms1.ServiceReference1.getResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apiretriever.dankest.ddns.net")]
    public partial class getResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public getResultRequestBody() {
        }
        
        public getResultRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://apiretriever.dankest.ddns.net", Order=0)]
        public WindowsForms1.ServiceReference1.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(WindowsForms1.ServiceReference1.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apiretriever.dankest.ddns.net")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getResultReturn;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(string getResultReturn) {
            this.getResultReturn = getResultReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIRetrieverChannel : WindowsForms1.ServiceReference1.APIRetriever, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIRetrieverClient : System.ServiceModel.ClientBase<WindowsForms1.ServiceReference1.APIRetriever>, WindowsForms1.ServiceReference1.APIRetriever {
        
        public APIRetrieverClient() {
        }
        
        public APIRetrieverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIRetrieverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIRetrieverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIRetrieverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsForms1.ServiceReference1.getResultResponse WindowsForms1.ServiceReference1.APIRetriever.getResult(WindowsForms1.ServiceReference1.getResultRequest request) {
            return base.Channel.getResult(request);
        }
        
        public string getResult(string city) {
            WindowsForms1.ServiceReference1.getResultRequest inValue = new WindowsForms1.ServiceReference1.getResultRequest();
            inValue.Body = new WindowsForms1.ServiceReference1.getResultRequestBody();
            inValue.Body.city = city;
            WindowsForms1.ServiceReference1.getResultResponse retVal = ((WindowsForms1.ServiceReference1.APIRetriever)(this)).getResult(inValue);
            return retVal.Body.getResultReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsForms1.ServiceReference1.getResultResponse> WindowsForms1.ServiceReference1.APIRetriever.getResultAsync(WindowsForms1.ServiceReference1.getResultRequest request) {
            return base.Channel.getResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsForms1.ServiceReference1.getResultResponse> getResultAsync(string city) {
            WindowsForms1.ServiceReference1.getResultRequest inValue = new WindowsForms1.ServiceReference1.getResultRequest();
            inValue.Body = new WindowsForms1.ServiceReference1.getResultRequestBody();
            inValue.Body.city = city;
            return ((WindowsForms1.ServiceReference1.APIRetriever)(this)).getResultAsync(inValue);
        }
    }
}
